---
title: "Media"
editor: 
  markdown: 
    wrap: 72
---

### **2025**

["Birds, Sex &
Beauty"](https://www.amazon.ca/Birds-Sex-Beauty-Extraordinary-Implications/dp/0063342987/ref=tmm_hrd_swatch_0)
by Matt Ridley, Harper

["The Well-Connected
Animal"](https://www.amazon.ca/Well-Connected-Animal-Networks-Complexity-Societies/dp/0226818780/ref=sr_1_1?crid=3EOBHJI22V75I&dib=eyJ2IjoiMSJ9.0OGELD5Rsj6WVtxu8afSaUnRdfQIhQe1ShF7XgehskbGjHj071QN20LucGBJIEps.zHqnr3KzBGnZPoVQFDCzr8q299l6k4h1YFX1_2AzYWo&dib_tag=se&keywords=the+well-connected+animal&qid=1769697855&s=books&sprefix=the+well-connected+animal%2Cstripbooks%2C109&sr=1-1)
by Lee Alan Dugatkin, University of Chicago Press

### **2024**

*Competition in birds…* [Living Bird
magazine](https://www.allaboutbirds.org/news/who-wins-at-the-bird-feeder-the-lone-wolf-or-the-social-butterfly/)

*Hummingbird flight control…* [Scientific
American](https://www.scientificamerican.com/article/hummingbirds-control-their-flight-with-a-newfound-mechanism/)

*On the wings of war…* [New York
Times](https://www.nytimes.com/2024/11/26/science/hummingbirds-robots-drone-warfare.html)

### **2023**

*Social species are featherweights…* [Audubon
magazine](https://www.audubon.org/news/in-bird-feeder-battles-social-species-are-featherweights),
[Birdwatching
Daily](https://www.birdwatchingdaily.com/news/science/at-bird-feeders-theres-strength-in-numbers/),
Calgary QR 107.3 Radio

*Bird collisions…* [British Ornithologists’
Union](https://bou.org.uk/?p=68350&preview=true)

### **2022**

*Peacock behaviour…* [Audubon
magazine](https://www.audubon.org/magazine/summer-2022/california-has-peacock-problem)

["An Immense
World"](https://www.amazon.ca/Immense-World-Animal-Senses-Reveal/dp/1039003907/ref=sr_1_1?crid=1E62ENH56LFL1&keywords=an+immense+world&qid=1663267945&sprefix=an+immense+world%2Caps%2C136&sr=8-1)
by Ed Yong, Knopf

["The Sounds of
Life"](https://www.amazon.ca/Sounds-Life-Digital-Technology-Bringing/dp/0691206287/ref=sr_1_1?crid=2BO17IMCHH6UG&keywords=karen+bakker&qid=1683567856&sprefix=karen+%2Caps%2C468&sr=8-1)
by Karen Bakker, Princeton University Press

### **2021**

*Peacock behaviour…* in the book ["Why
Peacocks?"](https://www.amazon.ca/Why-Peacocks-Unlikely-Meaning-Magnificent/dp/1982101075)
by Sean Flynn, Simon & Schuster

*Weighted restraint…* project with Campbell and Adler of Carleton
Engineering [New York
Times](https://www.nytimes.com/2021/12/26/us/police-deaths-in-custody-blame.html)

### **2020**

*Hummingbird flight…* National Geographic Spain

#ScientistFridays Discover Canada… Yuchao Wang talks about our research
on peacock colour

*Social network stability…* [The Ottawa
Citizen](https://ottawacitizen.com/news/local-news/for-bird-and-humans-more-friends-doesnt-mean-better-friends),
The Charlatan

CJBQ Newsmaker Sunday (radio, February 16)

*Peacock behaviour…*
[Joivert.com](https://www.joivert.com/animals/peacock-birds-flock-to-the-burbs/)

### **2019**

[Birdnote](https://www.birdnote.org/show/peacocks-tail-more-meets-eye)
(US public radio and
[Audubon](https://www.audubon.org/news/hear-sound-peacock-love-made-trembling-feathers))

CKCU Radio 93.1 (May 28)

CBC Radio’s Fresh Air (May 19)

BBC’s 30 Animals That Made Us Smarter (radio, September 2019)

### **2018**

*The peafowl’s crest feathers are tuned to social displays…*
[Science](https://www.sciencemag.org/news/2018/11/watch-peacock-get-female-s-attention-making-her-head-vibrate),
[New
Scientist](https://www.newscientist.com/article/2171907-male-peacocks-can-make-females-heads-vibrate-at-a-distance/),
[Daily
Mail](https://www.dailymail.co.uk/sciencetech/article-5858705/Hello-ladies-Male-peacocks-make-females-heads-vibrate-distance.html),
[The
Atlantic](https://www.theatlantic.com/science/archive/2018/12/peacock-crests-are-vibration-sensors/578656/),
[Scientific American 60-Second
Science](https://www.scientificamerican.com/podcast/episode/colorful-peacocks-impress-females-with-good-vibes/)

*Maneuvering ability in hummingbirds…*
[Science](http://www.sciencemag.org/news/2018/02/high-speed-cameras-reveal-how-hummingbirds-can-turn-dime),
[Science
News](https://www.sciencenews.org/article/trove-hummingbird-flight-data-reveals-secrets-nimble-flying),
[Seeker](https://www.seeker.com/animals/the-secrets-of-hummingbird-agility-revealed),
[Daily
Mail](http://www.dailymail.co.uk/sciencetech/article-5367669/Large-hummingbirds-just-good-flyers-smaller-ones.html),
[BBC](http://www.bbc.co.uk/programmes/w3csvrh5),
[CBC](http://www.cbc.ca/news/canada/british-columbia/flight-of-the-hummingbird-how-size-and-wing-shape-forge-fantastic-flyers-1.4529578)

[BBC/PBS Natural Born
Rebels](https://youtu.be/SLrIGJRv38Y?si=xvLK62PC8iF16tRU), research in
[Episode 3 “The Mating
Game”](https://www.pbs.org/video/natural-born-rebels-episode-3-zx3pk6/)

*Peacocks accused of fowl play*… Vancouver Weekly

### **2017**

[Unlocking the secrets behind the hummingbird’s
frenzy,](http://www.nationalgeographic.com/magazine/2017/07/hummingbird-secrets-speed-worlds-smallest-bird/)
National Geographic story and photo series

### **2016**

*Visual guidance of forward flight in hummingbirds…*
[Gizmodo](http://gizmodo.com/hummingbird-flight-is-more-amazing-than-we-realized-1783825300),
[Christian Science
Monitor](https://www.csmonitor.com/Science/2016/0719/How-do-hummingbirds-navigate-at-such-high-speeds-without-crashing),
[Vancouver
Sun](http://vancouversun.com/news/local-news/hummingbirds-process-the-world-differently-ubc-study-finds),
BBC Radio, City TV

*Biomechanics of the peacock’s display…* [New York Times/Science
Take](https://www.nytimes.com/2016/04/28/science/peacocksdont-just-show-their-feathers-they-rattle-them.html),
[Quirks and
Quarks](http://www.cbc.ca/radio/quirks/quirks-quarks-for-apr-30-2016-1.3559345/the-peacock-makes-eye-contact-with-its-tail-1.3559467),
[Science
News](https://www.sciencenews.org/article/peacocks-twerk-shake-their-tail-feathers),
[Christian Science
Monitor](https://www.csmonitor.com/Science/2016/0428/Peacock-feather-physics-How-this-train-rattling-display-might-woo-potential-mates),
[Gizmodo](http://gizmodo.com/the-physics-of-peacock-tail-feathers-is-even-more-dazzl-1772653586),
[Wall Street
Journal](http://www.wsj.com/video/the-physics-of-a-peacock-shimmering-mating-dance/9A012834-6689-464E-9A89-C8654C3C4594.html),
[Nature Research
Highlights](http://www.nature.com/nature/journal/v533/n7601/full/533010a.html?foxtrotcallback=true),
Scientific American,
[Discover](https://www.discovermagazine.com/train-rattling-peacocks-are-biomechanical-wonders-11460),
[Tech
Times](https://www.techtimes.com/articles/154758/20160429/the-science-behind-peacock-feathers-and-how-it-attracts-mates.htm),
PBS Newshour

### **2014**

*Deceptive copulation calls…* [Quirks and
Quarks](http://www.cbc.ca/radio/quirks/quirks-quarks-for-march-22-2014-1.2842969/peacocks-give-a-hoot-about-sex-1.2842970),
BBC Nature News, [Science
News](https://www.sciencenews.org/article/peacocks-sometimes-fake-mating-hoots),
[National
Geographic](https://drive.google.com/file/d/1ccV0WIKNEZdexnNkVFnzzIkQwV4YNCQ1/view?usp=sharing),
[NPR’s Wait Wait… Don’t Tell Me! (March
22)](http://www.npr.org/2014/03/22/292588683/panel-round-two)

CBC’s The Nature of Things “[Decoding
Desire](https://www.imdb.com/title/tt4585786/)”, TV documentary

### **2013 and earlier**

*Eye for an eyespot: how iridescent ocelli influence peacock mating
success…*
[Slate](http://www.slate.com/blogs/wild_things/2015/08/17/peacock_evolution_through_sexual_selection_feathers_sounds_eye_tracking.html),
[Science
News](https://onlinelibrary.wiley.com/doi/abs/10.1002/scin.2008.5591731819)

*Peahens prefer peacocks displaying more eyespots…*
[Nature](http://www.nature.com/news/2011/180411/full/news.2011.245.html),
[Wired](https://www.wired.com/2011/04/peacock-mating-feathers/),
[Science
News](https://www.sciencenews.org/article/eyespots-have-it-after-all)

[Youtube](https://www.youtube.com/user/roslyndakin/videos?flow=grid&view=0&sort=p)

[Flickr](https://www.flickr.com/photos/24692065@N08/)
